import { BarChart3, CheckCheck, FlaskConical, RefreshCw, X } from "lucide-react";
import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

export function CommissionHistory() {
  const history = trpc.operations.commissionHistory.useQuery();
  const entries = history.data ?? [];
  const max = Math.max(...entries.map(entry => entry.commissionBps), 1);
  return <Card className="rounded-[26px] border-[#e0ece8]"><CardHeader className="flex-row items-center justify-between space-y-0"><div><CardTitle className="text-base text-[#193d3c]">Commission history</CardTitle><p className="mt-1 text-xs text-[#89a19d]">Platform share changes recorded over time</p></div><BarChart3 className="h-5 w-5 text-[#76a49b]" /></CardHeader><CardContent>{entries.length ? <div className="flex h-44 items-end gap-2 overflow-x-auto pb-7">{entries.map(entry => <div key={entry.id} className="group relative flex h-full min-w-[28px] flex-1 flex-col justify-end"><div className="absolute -top-5 left-1/2 -translate-x-1/2 text-[9px] font-black text-[#4c887c] opacity-0 transition group-hover:opacity-100">{(entry.commissionBps / 100).toFixed(0)}%</div><div className="rounded-t-lg bg-[#4e9c87] transition group-hover:bg-[#f4b942]" style={{ height: `${Math.max(8, (entry.commissionBps / max) * 100)}%` }} /><div className="absolute -bottom-6 left-1/2 -translate-x-1/2 whitespace-nowrap text-[9px] text-[#8ca39e]">{new Date(entry.createdAt).toLocaleDateString("en-NG", { day: "2-digit", month: "short" })}</div></div>)}</div> : <div className="rounded-2xl border border-dashed border-[#cfe2db] p-10 text-center text-sm text-[#87a09a]">No commission changes recorded yet.</div>}</CardContent></Card>;
}

export function BulkDocumentReview() {
  const utils = trpc.useUtils();
  const documents = trpc.operations.driverDocuments.useQuery();
  const [selected, setSelected] = useState<number[]>([]);
  const bulk = trpc.operations.bulkReviewDocuments.useMutation({ onSuccess: async result => { toast.success(`${result.count} document${result.count === 1 ? "" : "s"} updated`); setSelected([]); await utils.operations.driverDocuments.invalidate(); } });
  const pending = documents.data ?? [];
  const toggle = (id: number) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]);
  return <Card className="rounded-[26px] border-[#e0ece8]"><CardHeader className="flex-row items-center justify-between space-y-0"><div><CardTitle className="text-base text-[#193d3c]">Bulk document review</CardTitle><p className="mt-1 text-xs text-[#89a19d]">Select several pending documents and decide once</p></div><Badge className="bg-[#eef7f3] text-[#458877] hover:bg-[#eef7f3]">{selected.length} selected</Badge></CardHeader><CardContent className="space-y-3">{pending.length ? <><div className="flex gap-2"><Button size="sm" onClick={() => bulk.mutate({ documentIds: selected, decision: "approved" })} disabled={!selected.length || bulk.isPending} className="rounded-lg bg-[#3f967f] text-white hover:bg-[#347f6c]"><CheckCheck className="mr-1.5 h-3.5 w-3.5" /> Approve selected</Button><Button size="sm" variant="outline" onClick={() => bulk.mutate({ documentIds: selected, decision: "rejected", rejectionReason: "Please upload a clearer document" })} disabled={!selected.length || bulk.isPending} className="rounded-lg border-[#edc5bd] text-[#bd7063]"><X className="mr-1.5 h-3.5 w-3.5" /> Reject selected</Button></div>{pending.map(document => <label key={document.id} className="flex cursor-pointer items-center gap-3 rounded-xl bg-[#f6faf8] p-3"><input type="checkbox" checked={selected.includes(document.id)} onChange={() => toggle(document.id)} className="h-4 w-4 accent-[#3f967f]" /><div className="min-w-0 flex-1"><div className="truncate text-sm font-bold text-[#42635e]">{document.documentType.replaceAll("_", " ")}</div><div className="text-[10px] text-[#8ca39e]">Driver #{document.driverId} · {document.originalFileName}</div></div><a href={document.url} target="_blank" rel="noreferrer" onClick={event => event.stopPropagation()} className="text-xs font-bold text-[#3f8b79] underline">Open</a></label>)}</> : <div className="rounded-2xl border border-dashed border-[#cfe2db] p-8 text-center text-sm text-[#87a09a]">No pending documents to batch review.</div>}</CardContent></Card>;
}

export function SandboxPaymentTest() {
  const [accountNumber, setAccountNumber] = useState("");
  const [customerReference, setCustomerReference] = useState("");
  const [amount, setAmount] = useState("1000");
  const [transactionReference, setTransactionReference] = useState(() => `SANDBOX-${Date.now()}`);
  const [status, setStatus] = useState<"SUCCESSFUL" | "PENDING" | "FAILED" | "REVERSED">("SUCCESSFUL");
  const test = trpc.operations.sandboxPayment.useMutation({ onSuccess: result => toast.success("Sandbox webhook processed") });
  return <Card className="rounded-[26px] border-[#e0ece8]"><CardHeader><CardTitle className="flex items-center gap-2 text-base text-[#193d3c]"><FlaskConical className="h-5 w-5 text-[#c18d28]" /> Monnify sandbox payment test</CardTitle><p className="mt-1 text-xs leading-relaxed text-[#89a19d]">Simulates a signed-provider event in sandbox mode. Use a Kkary reserved account number or customer reference.</p></CardHeader><CardContent><form onSubmit={event => { event.preventDefault(); test.mutate({ accountNumber: accountNumber || undefined, customerReference: customerReference || undefined, amountKobo: Math.round(Number(amount) * 100), transactionReference, status }); }} className="grid gap-3 sm:grid-cols-2"><Input value={accountNumber} onChange={event => setAccountNumber(event.target.value)} placeholder="Reserved account number" className="h-11 rounded-xl" /><Input value={customerReference} onChange={event => setCustomerReference(event.target.value)} placeholder="Customer reference" className="h-11 rounded-xl" /><Input value={amount} onChange={event => setAmount(event.target.value)} type="number" min="1" placeholder="Amount (₦)" className="h-11 rounded-xl" /><select value={status} onChange={event => setStatus(event.target.value as typeof status)} className="h-11 rounded-xl border border-[#dcebe5] bg-white px-3 text-sm"><option value="SUCCESSFUL">Successful</option><option value="PENDING">Pending</option><option value="FAILED">Failed</option><option value="REVERSED">Reversed</option></select><Input value={transactionReference} onChange={event => setTransactionReference(event.target.value)} placeholder="Transaction reference" className="h-11 rounded-xl sm:col-span-2" /><Button disabled={test.isPending || (!accountNumber && !customerReference)} className="h-11 rounded-xl bg-[#113a3b] text-white sm:col-span-2">{test.isPending ? "Sending test event…" : "Send sandbox webhook"}<RefreshCw className="ml-auto h-4 w-4" /></Button></form>{test.data && <pre className="mt-4 overflow-auto rounded-xl bg-[#123b3b] p-3 text-[10px] text-[#c8e5dc]">{JSON.stringify(test.data, null, 2)}</pre>}</CardContent></Card>;
}
